services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shopping_helper
      POSTGRES_USER: shopping
      POSTGRES_PASSWORD: shopping
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
